// <auto-generated />
using System;
using BlogApp.Data.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogApp.Data.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BlogApp.Entities.Concrete.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CommentCont")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SeoAuthor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SeoTags")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CommentCont = 57,
                            Content = "C# 9.0 introduces record types. You use the record keyword to define a reference type that provides built-in functionality for encapsulating data. You can create record types with immutable properties by using positional parameters or standard property syntax:",
                            CreatedDate = new DateTime(2022, 1, 13, 20, 57, 47, 432, DateTimeKind.Local).AddTicks(6511),
                            CreatedName = "InitialCreate",
                            Date = new DateTime(2022, 1, 13, 20, 57, 47, 432, DateTimeKind.Local).AddTicks(4985),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2022, 1, 13, 20, 57, 47, 432, DateTimeKind.Local).AddTicks(6770),
                            ModifiedName = "InitialCreate",
                            Note = "C# 9.0 news",
                            SeoAuthor = "Ali Duman",
                            SeoDescription = "What are new on C# 9.0",
                            SeoTags = "C#, C# 9.0, C# news",
                            Thumbnail = "Default.jpg",
                            Title = "What are new on C# 9.0",
                            UserId = 1,
                            ViewCount = 4332
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CommentCont = 32,
                            Content = "C++11 is a version of the ISO/IEC 14882 standard for the C++ programming language. C++11 replaced the prior version of the C++ standard, called C++03,[1] and was later replaced by C++14. The name follows the tradition of naming language versions by the publication year of the specification, though it was formerly named C++0x because it was expected to be published before 2010.",
                            CreatedDate = new DateTime(2022, 1, 13, 20, 57, 47, 432, DateTimeKind.Local).AddTicks(8113),
                            CreatedName = "InitialCreate",
                            Date = new DateTime(2022, 1, 13, 20, 57, 47, 432, DateTimeKind.Local).AddTicks(8111),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2022, 1, 13, 20, 57, 47, 432, DateTimeKind.Local).AddTicks(8114),
                            ModifiedName = "InitialCreate",
                            Note = "C++ 11.0 news",
                            SeoAuthor = "Ali Duman",
                            SeoDescription = "What are news on C++ 11",
                            SeoTags = "C++, C++ 11.0, C++ news",
                            Thumbnail = "Default.jpg",
                            Title = "Briliant changes on C++ 11.0",
                            UserId = 1,
                            ViewCount = 2701
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CommentCont = 13,
                            Content = "ECMAScript 2015 was the second major revision to JavaScript.ECMAScript 2015 is also known as ES6 and ECMAScript 6.This chapter describes the most important features of ES6.",
                            CreatedDate = new DateTime(2022, 1, 13, 20, 57, 47, 432, DateTimeKind.Local).AddTicks(8120),
                            CreatedName = "InitialCreate",
                            Date = new DateTime(2022, 1, 13, 20, 57, 47, 432, DateTimeKind.Local).AddTicks(8119),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2022, 1, 13, 20, 57, 47, 432, DateTimeKind.Local).AddTicks(8121),
                            ModifiedName = "InitialCreate",
                            Note = "ES6 news",
                            SeoAuthor = "Ali Duman",
                            SeoDescription = "What are news on ES6",
                            SeoTags = "Javascript, ES6, Javascript ES6",
                            Thumbnail = "Default.jpg",
                            Title = "What are news on ES6",
                            UserId = 1,
                            ViewCount = 1003
                        });
                });

            modelBuilder.Entity("BlogApp.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Note")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 1, 13, 20, 57, 47, 435, DateTimeKind.Local).AddTicks(2183),
                            CreatedName = "InitialCreate",
                            Description = "Everthing about C# programming language",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2022, 1, 13, 20, 57, 47, 435, DateTimeKind.Local).AddTicks(2197),
                            ModifiedName = "InitialCreate",
                            Name = "C#",
                            Note = "C# Programming Language"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 1, 13, 20, 57, 47, 435, DateTimeKind.Local).AddTicks(2221),
                            CreatedName = "InitialCreate",
                            Description = "Everthing about C++ programming language",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2022, 1, 13, 20, 57, 47, 435, DateTimeKind.Local).AddTicks(2222),
                            ModifiedName = "InitialCreate",
                            Name = "C++",
                            Note = "C++ Programming Language"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 1, 13, 20, 57, 47, 435, DateTimeKind.Local).AddTicks(2226),
                            CreatedName = "InitialCreate",
                            Description = "Everthing about Javascript programming language",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2022, 1, 13, 20, 57, 47, 435, DateTimeKind.Local).AddTicks(2227),
                            ModifiedName = "InitialCreate",
                            Name = "Javascript",
                            Note = "Javascript Programming Language"
                        });
                });

            modelBuilder.Entity("BlogApp.Entities.Concrete.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 1,
                            CreatedDate = new DateTime(2022, 1, 13, 20, 57, 47, 437, DateTimeKind.Local).AddTicks(409),
                            CreatedName = "InitialCreate",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2022, 1, 13, 20, 57, 47, 437, DateTimeKind.Local).AddTicks(426),
                            ModifiedName = "InitialCreate",
                            Note = "C# Comment",
                            Text = "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)"
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 1,
                            CreatedDate = new DateTime(2022, 1, 13, 20, 57, 47, 437, DateTimeKind.Local).AddTicks(458),
                            CreatedName = "InitialCreate",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2022, 1, 13, 20, 57, 47, 437, DateTimeKind.Local).AddTicks(459),
                            ModifiedName = "InitialCreate",
                            Note = "C# Comment",
                            Text = "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc."
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 2,
                            CreatedDate = new DateTime(2022, 1, 13, 20, 57, 47, 437, DateTimeKind.Local).AddTicks(464),
                            CreatedName = "InitialCreate",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2022, 1, 13, 20, 57, 47, 437, DateTimeKind.Local).AddTicks(465),
                            ModifiedName = "InitialCreate",
                            Note = "C++ Comment",
                            Text = "Phasellus eu vehicula massa. Sed viverra ut dui ac lacinia. Aenean vestibulum eget ex vel finibus. Morbi non porttitor metus. Nam rhoncus quam vitae quam elementum tincidunt. Fusce vel eros tempus, ullamcorper massa vitae, varius nunc. In ut bibendum diam. Duis sit amet vestibulum lectus. Morbi lacinia quam vitae viverra condimentum. In porta, augue id pharetra cursus, odio felis molestie turpis, sit amet scelerisque urna ex sed neque."
                        },
                        new
                        {
                            Id = 4,
                            ArticleId = 3,
                            CreatedDate = new DateTime(2022, 1, 13, 20, 57, 47, 437, DateTimeKind.Local).AddTicks(469),
                            CreatedName = "InitialCreate",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2022, 1, 13, 20, 57, 47, 437, DateTimeKind.Local).AddTicks(470),
                            ModifiedName = "InitialCreate",
                            Note = "Javascript Comment",
                            Text = "Aenean finibus nibh at purus dictum, quis condimentum eros viverra. Proin sed imperdiet dolor. Maecenas at est risus. Quisque commodo tortor eu ligula porttitor feugiat ut id nulla. Fusce et volutpat nibh, id ultrices diam. Sed est sem, consequat in arcu et, consequat eleifend orci. Pellentesque dignissim nec ex bibendum tincidunt."
                        });
                });

            modelBuilder.Entity("BlogApp.Entities.Concrete.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 1, 13, 20, 57, 47, 438, DateTimeKind.Local).AddTicks(7710),
                            CreatedName = "InitialCreate",
                            Description = "Access anywhere",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2022, 1, 13, 20, 57, 47, 438, DateTimeKind.Local).AddTicks(7726),
                            ModifiedName = "InitialCreate",
                            Name = "Admin",
                            Note = "Admin Role"
                        });
                });

            modelBuilder.Entity("BlogApp.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARBINARY(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 1, 13, 20, 57, 47, 444, DateTimeKind.Local).AddTicks(6331),
                            CreatedName = "InitialCreate",
                            Email = "alidmn@gmail.com",
                            FirstName = "Ali",
                            Image = "default.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Duman",
                            ModifiedDate = new DateTime(2022, 1, 13, 20, 57, 47, 444, DateTimeKind.Local).AddTicks(6346),
                            ModifiedName = "InitialCreate",
                            Note = "User",
                            PasswordHash = new byte[] { 48, 49, 57, 50, 48, 50, 51, 97, 55, 98, 98, 100, 55, 51, 50, 53, 48, 53, 49, 54, 102, 48, 54, 57, 100, 102, 49, 56, 98, 53, 48, 48 },
                            RoleId = 1,
                            UserName = "alidmn"
                        });
                });

            modelBuilder.Entity("BlogApp.Entities.Concrete.Article", b =>
                {
                    b.HasOne("BlogApp.Entities.Concrete.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogApp.Entities.Concrete.User", "User")
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlogApp.Entities.Concrete.Comment", b =>
                {
                    b.HasOne("BlogApp.Entities.Concrete.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("BlogApp.Entities.Concrete.User", b =>
                {
                    b.HasOne("BlogApp.Entities.Concrete.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BlogApp.Entities.Concrete.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BlogApp.Entities.Concrete.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("BlogApp.Entities.Concrete.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BlogApp.Entities.Concrete.User", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
